<a href="https://colab.research.google.com/github/LucasCarmusciano/DeepLearning/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [11]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 3s 10ms/step - loss: 54933.2617
Epoch 2/100
240/240 [==============================] - 2s 7ms/step - loss: 189.5294
Epoch 3/100
240/240 [==============================] - 2s 7ms/step - loss: 184.7913
Epoch 4/100
240/240 [==============================] - 2s 7ms/step - loss: 181.6550
Epoch 5/100
240/240 [==============================] - 2s 8ms/step - loss: 177.7989
Epoch 6/100
240/240 [==============================] - 1s 6ms/step - loss: 172.8554
Epoch 7/100
240/240 [==============================] - 2s 8ms/step - loss: 167.7094
Epoch 8/100
240/240 [==============================] - 1s 6ms/step - loss: 162.1764
Epoch 9/100
240/240 [==============================] - 2s 9ms/step - loss: 155.8680
Epoch 10/100
240/240 [==============================] - 2s 8ms/step - loss: 148.8551
Epoch 11/100
240/240 [==============================] - 1s 6ms/step - loss: 141.4910
Epoch 12/100
240/240 [==============================] - 1s 6ms/step - l

### Predicting the result of a single observation

In [12]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 [==============================] - 0s 2ms/step
[[431.05 431.23]
 [462.03 460.01]
 [465.57 461.14]
 ...
 [473.07 473.26]
 [439.37 438.  ]
 [458.86 463.28]]
